Repository pressbooks/pressbooks-book, pull requests merged in 2018-11, with the labels that each got.

#296 Use short title for webbook navigation, with title as fallback (resolves PB-14997)
  assets/src/styles/layouts/_footer.scss
  assets/src/styles/layouts/_reading.scss
  dist/mix-manifest.json
  dist/scripts/sharer.js
  dist/styles/book.css
  inc/helpers/namespace.php
Labels: enhancement

#359 Add link differention for print/digital (fix #317)
  assets/styles/components/_colors.scss
  assets/styles/components/_elements.scss
  packages/buckram/assets/styles/components/_colors.scss
  packages/buckram/assets/styles/components/elements/_links.scss
  packages/buckram/assets/styles/variables/_colors.scss
  packages/buckram/assets/styles/variables/_elements.scss
Labels: a11y, buckram, enhancement

#358 Move subsection caching to core (fix pressbooks/pressbooks#1438)
  inc/helpers/namespace.php
  partials/content-toc.php
  tests/test-helpers.php
Labels: enhancement

#360 Address errors in running content compilation (fix #310, fix #311)
  packages/buckram/assets/styles/components/structure/_mixins.scss
  packages/buckram/assets/styles/variables/_structure.scss
  packages/buckram/package-lock.json
Labels: buckram, bug

#361 Style glossary outputs (fix #320)
  assets/styles/components/_elements.scss
  packages/buckram/assets/styles/components/elements/_lists.scss
  packages/buckram/assets/styles/variables/_elements.scss
Labels: buckram, enhancement

#370 Add site icon
  assets/src/images/android-chrome-192x192.png
  assets/src/images/android-chrome-512x512.png
  assets/src/images/apple-touch-icon-120x120.png
  assets/src/images/apple-touch-icon-152x152.png
  assets/src/images/apple-touch-icon-180x180.png
  assets/src/images/apple-touch-icon-60x60.png
  assets/src/images/apple-touch-icon-76x76.png
  assets/src/images/apple-touch-icon.png
  assets/src/images/favicon-16x16.png
  assets/src/images/favicon-32x32.png
  assets/src/images/favicon.ico
  assets/src/images/mstile-144x144.png
  assets/src/images/mstile-150x150.png
  assets/src/images/mstile-310x150.png
  assets/src/images/mstile-310x310.png
  assets/src/images/mstile-70x70.png
  assets/src/images/safari-pinned-tab.svg
  browserconfig.xml
  dist/images/android-chrome-192x192.png
  dist/images/android-chrome-512x512.png
  dist/images/apple-touch-icon-120x120.png
  dist/images/apple-touch-icon-152x152.png
  dist/images/apple-touch-icon-180x180.png
  dist/images/apple-touch-icon-60x60.png
  dist/images/apple-touch-icon-76x76.png
  dist/images/apple-touch-icon.png
  dist/images/favicon-16x16.png
  dist/images/favicon-32x32.png
  dist/images/favicon.ico
  dist/images/mstile-144x144.png
  dist/images/mstile-150x150.png
  dist/images/mstile-310x150.png
  dist/images/mstile-310x310.png
  dist/images/mstile-70x70.png
  dist/images/safari-pinned-tab.svg
  favicon.ico
  header.php
  site.webmanifest
Labels: enhancement

#371 Only apply TOC colour variables in print PDF (fix #317)
  packages/buckram/assets/styles/components/toc/_generic.scss
  packages/buckram/package-lock.json
Labels: a11y, enhancement

#373 Fix reading footer icon size (resolves #372)
  dist/mix-manifest.json
  dist/styles/book.css
  packages/aetna/assets/styles/components/_social.scss
Labels: bug

#374 Fix issue where floated image margins were ignored (closes #236)
  packages/buckram/assets/styles/components/media/_images.scss
Labels: buckram, bug

#376 Fix issue with navigation when there's a discrepancy between title lengths
  CHANGELOG.md
  assets/src/styles/layouts/_reading.scss
  dist/mix-manifest.json
  dist/styles/book.css
Labels: bug

#377 Fix license icon (closes #372)
  dist/mix-manifest.json
  dist/styles/book.css
  packages/aetna/assets/styles/components/_social.scss
Labels: bug

#379 Refine webbook table of contents (fix #378)
  CHANGELOG.md
  assets/src/scripts/routes/common.js
  assets/src/scripts/routes/single.js
  assets/src/styles/components/_toc.scss
  dist/mix-manifest.json
  dist/scripts/book.js
  dist/styles/book.css
  inc/actions/namespace.php
  package.json
  partials/content-cover-toc.php
Labels: enhancement

#381 Load Hypothesis plugin options into config object (fix #380)
  CHANGELOG.md
  assets/src/scripts/pane.js
  dist/mix-manifest.json
  dist/scripts/pane.js
  inc/actions/namespace.php
  package.json
Labels: bug

#382 Add spacing between front matter, parts, and back matter in TOC (resolves #292)
  CHANGELOG.md
  assets/src/styles/components/_toc.scss
  dist/mix-manifest.json
  dist/styles/book.css
Labels: enhancement

#375 Numberless chapter targets before content
  packages/buckram/assets/styles/components/section-titles/_chapters.scss
Labels: buckram, bug

#365 Add support for maps on part title align (fix #364)
  packages/buckram/assets/styles/components/section-titles/_parts.scss
  packages/buckram/assets/styles/variables/_section-titles.scss
Labels: buckram, enhancement
