Repository pressbooks/pressbooks-book, pull requests merged in 2019-02, with the labels that each got.

#487 Remove vertical scrolling from pre elements
  packages/aetna/assets/styles/common/_reboot.scss
Labels: bug

#491 Don't include paginated chapter nav in collapsed sections (fix #489)
  assets/src/scripts/collapse-sections.js
  dist/mix-manifest.json
  dist/scripts/collapse-sections.js
  dist/styles/book.css
Labels: bug

#490 Fall back to shaded variable for textbox colours
  packages/buckram/assets/styles/components/_colors.scss
  packages/buckram/assets/styles/components/specials/_textboxes.scss
  packages/buckram/assets/styles/variables/_colors.scss
  packages/buckram/assets/styles/variables/_specials.scss
Labels: buckram, bug

#493 Move get_name_for_filetype() to core
  inc/helpers/namespace.php
  partials/content-cover-book-header.php
  tests/test-helpers.php
Labels: enhancement

#494 Fix vertical pre scrolling (resolves #487)
  dist/mix-manifest.json
  dist/styles/book.css
  packages/aetna/assets/styles/common/_reboot.scss
  packages/buckram/assets/styles/variables/_elements.scss
Labels: buckram, bug

#497 Center interactivate content fallback images
  packages/buckram/assets/styles/components/media/_interactive-content.scss
Labels: buckram, bug

#498 Add JSON-LD metadata to webbook (resolves #434)
  functions.php
  inc/actions/namespace.php
  tests/test-actions.php
Labels: enhancement

#500 Remove Gutenberg block styles
  inc/actions/namespace.php
Labels: enhancement

#499 Add citation metadata, cleanup deprecated metadata (fix #435)
  functions.php
  header.php
  inc/actions/namespace.php
Labels: enhancement

#501 Add $section-author-text-indent variable
  packages/buckram/CHANGELOG.md
  packages/buckram/assets/styles/components/section-titles/_back-matter.scss
  packages/buckram/assets/styles/components/section-titles/_chapters.scss
  packages/buckram/assets/styles/components/section-titles/_front-matter.scss
  packages/buckram/assets/styles/components/section-titles/_generic.scss
  packages/buckram/assets/styles/variables/_section-titles.scss
Labels: buckram, enhancement

#503 Publisher float
  packages/buckram/CHANGELOG.md
  packages/buckram/assets/styles/components/pages/_titles.scss
  packages/buckram/assets/styles/variables/_pages.scss
Labels: buckram, enhancement

#502 Add dt color variable
  packages/buckram/CHANGELOG.md
  packages/buckram/assets/styles/components/elements/_lists.scss
  packages/buckram/assets/styles/variables/_colors.scss
Labels: buckram, enhancement

#508 Remove jQuery UI (fix #506)
  inc/actions/namespace.php
Labels: enhancement

#509 Only enqueue Hypothesis pane script if Hypothesis is used (fix #505)
  inc/actions/namespace.php
Labels: enhancement

#511 Remove scroll animation (fix #488)
  assets/src/scripts/routes/common.js
  assets/src/scripts/routes/single.js
  dist/mix-manifest.json
  dist/scripts/book.js
Labels: a11y, enhancement

#512 Use wp_text_diff() to improve comparison tool (fix pressbooks/pressbooks#1484)
  assets/src/scripts/book.js
  assets/src/scripts/routes/single.js
  assets/src/styles/components/_diff.scss
  dist/mix-manifest.json
  dist/scripts/book.js
  dist/styles/book.css
  functions.php
  inc/actions/namespace.php
  package-lock.json
  package.json
  partials/content-difftool.php
  tests/test-actions.php
Labels: enhancement

#504 Fix td border variable
  packages/buckram/CHANGELOG.md
  packages/buckram/assets/styles/components/elements/_tables.scss
  packages/buckram/assets/styles/variables/_colors.scss
  packages/buckram/assets/styles/variables/_elements.scss
Labels: buckram, bug

#513 Fix namespaces (resolves #507)
  comments.php
  functions.php
  header.php
  inc/actions/namespace.php
  inc/filters/namespace.php
  inc/helpers/namespace.php
  index.php
  page-about.php
  page-authors.php
  page-buy.php
  page-cover.php
  page.php
  partials/content-cover-book-header.php
  partials/content-cover-book-info.php
  partials/content-cover-metadata.php
  partials/content-difftool.php
  partials/content-toc.php
  search.php
  single.php
  tests/test-actions.php
  tests/test-helpers.php
Labels: enhancement

#514 Allow diffs to break on word boundaries (resolves #512)
  assets/src/styles/components/_diff.scss
  dist/mix-manifest.json
  dist/styles/book.css
Labels: enhancement

#522 Post intro blank pages
  packages/buckram/CHANGELOG.md
  packages/buckram/assets/styles/components/structure/_blank.scss
Labels: buckram, bug
